version: "3.0"

services:

  api:
    build:
      context: .
    image: microservice
    env_file: docker-compose.env
    environment:
      SERVICES: api
      PORT: 3000
    links:
      - nats
    depends_on:
      - nats
    labels:
      - "traefik.enable=true"   
      - "traefik.backend=api"
      - "traefik.port=3000"
      - "traefik.frontend.entryPoints=http"
      - "traefik.frontend.rule=PathPrefix:/"

  greeter:
    build:
      context: .
    image: microservice
    env_file: docker-compose.env
    environment:
      SERVICES:
        greeter
    links:
      - nats
    depends_on:
      - nats

  items:
    build:
      context: .
    image: microservice
    env_file: docker-compose.env
    environment:
      SERVICES:
        items
    links:
      - nats
    depends_on:
      - nats

  orders:
    build:
      context: .
    image: microservice
    env_file: docker-compose.env
    environment:
      SERVICES:
        orders
    links:
      - nats
    depends_on:
      - nats

  parcels:
    build:
      context: .
    image: microservice
    env_file: docker-compose.env
    environment:
      SERVICES:
        parcels
    links:
      - nats
    depends_on:
      - nats


  nats:
    image: nats

  traefik:
    image: traefik
    command: --web --docker --docker.domain=docker.localhost --logLevel=INFO --docker.exposedbydefault=false
    ports:
      - "3000:80"
      - "3001:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/null:/traefik.toml
