version: "3.0"

services:
  nats:
    image: nats
    ports:
      - "4222:4222"
      - "8222:8222"
    restart: unless-stopped

  traefik:
    image: "traefik"
    container_name: "traefik"
    restart: unless-stopped
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "4000:80"
      - "4001:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./traefik.toml:/etc/traefix/traefik.toml"

  rest:
    build:
      context: .
    image: microservice
    env_file: docker-compose.env
    environment:
      SERVICES: rest
      PORT: 3000
    links:
      - nats
    depends_on:
      - nats
    labels:
      - "traefik.enable=true"
      - "traefik.backend=rest"
      - "traefik.port=3000"
      - "traefik.frontend.entryPoints=http"
      - "traefik.frontend.rule=PathPrefix:/"
      - "traefik.http.routers.whoami.rule=Host(`whoami.localhost`)"
      - "traefik.http.routers.whoami.entrypoints=rest"

  greeter:
    build:
      context: .
    image: microservice
    env_file: docker-compose.env
    environment:
      SERVICES: greeter
    links:
      - nats
    depends_on:
      - nats
    labels:
      - "traefik.enable=true"
      - "traefik.backend=greeter"
      - "traefik.port=3000"
      - "traefik.frontend.entryPoints=http"
      - "traefik.frontend.rule=PathPrefix:/greeter"
      - "traefik.http.routers.whoami.rule=Host(`whoami.localhost`)"
      - "traefik.http.routers.whoami.entrypoints=web"

  items:
    build:
      context: .
    image: microservice
    env_file: docker-compose.env
    environment:
      SERVICES: items
    links:
      - nats
    depends_on:
      - nats

  orders:
    build:
      context: .
    image: microservice
    env_file: docker-compose.env
    environment:
      SERVICES: orders
    links:
      - nats
    depends_on:
      - nats

  parcels:
    build:
      context: .
    image: microservice
    env_file: docker-compose.env
    environment:
      SERVICES: parcels
    links:
      - nats
    depends_on:
      - nats
